import { VerticalBox } from "std-widgets.slint";
export component Example inherits Window {

    GridLayout {
        spacing: 25px;
        spacing-horizontal: 80px;
        padding: 50px;
        padding-left: 120px;
        padding-top: 75px;

        Row {

            Rectangle {
                background: rgb(59, 59, 84);
                border-width: 2px;
                border-radius: 10px;
                drop-shadow-blur: 2px;
                drop-shadow-color: grey;
                drop-shadow-offset-x: 1px;
                drop-shadow-offset-y: 1px;
        
                height: 175px;
                width: 300px;
        
                Image {
                    source: @image-url("images/default.jpg");
                    width: 150px;
                    horizontal-alignment: left;
                    x: -20px;
                }
                VerticalBox {
                    Text {
                        horizontal-alignment: right;
                        text: "Title";
                    }
                    Text {
                        horizontal-alignment: right;
                        text: "Username";
                    }
                    Text {
                        horizontal-alignment: right;
                        text: "Password";
                    }
                }
            }

            Rectangle {
                background: rgb(59, 59, 84);
                border-width: 2px;
                border-radius: 10px;
                drop-shadow-blur: 2px;
                drop-shadow-color: grey;
                drop-shadow-offset-x: 1px;
                drop-shadow-offset-y: 1px;
        
                height: 175px;
                width: 300px;
        
                Image {
                    source: @image-url("images/default.jpg");
                    width: 150px;
                    horizontal-alignment: left;
                    x: -20px;
                }
                VerticalBox {
                    Text {
                        horizontal-alignment: right;
                        text: "Title";
                    }
                    Text {
                        horizontal-alignment: right;
                        text: "Username";
                    }
                    Text {
                        horizontal-alignment: right;
                        text: "Password";
                    }
                }
            }

        }
    }
}